package ru.samokhin.labCheck.adapter.bot.model.newUser;

public enum RegistrationState {
    REGISTRATION_AWAITING_FIRST_NAME,
    REGISTRATION_AWAITING_LAST_NAME,
    REGISTRATION_AWAITING_PATRONYMIC,
    REGISTRATION_AWAITING_STUDENT_CARD,
    REGISTRATION_AWAITING_EMAIL,
    REGISTRATION_AWAITING_STUDENT_GROUP,
    REGISTRATION_COMPLETED
}
