package ru.samokhin.labCheck.adapter.bot.model.teacher.createTask;

public enum CreateTaskState {
    CREATE_TASK_AWAITING_TASK_NAME,
    CREATE_TASK_AWAITING_TASK_DESCRIPTION,
    CREATE_TASK_AWAITING_ASSIGNMENT_GROUP_NAME,
    CREATE_TASK_AWAITING_STUDENT_GROUP,
    CREATE_TASK_AWAITING_MORE_STUDENT_GROUP,
    CREATE_TASK_AWAITING_TEST_NAME,
    CREATE_TASK_AWAITING_TEST,
    CREATE_TASK_AWAITING_MORE_TEST,
    CREATE_TASK_FILL_DATA,
    CREATE_TASK_COMPLETED
}
